### ISSUE TITLE
SERVICE: invalid indirect expansion

### ISSUE THREAD

**Issue by lelu0** [smsapi/smsapi-bash-client#6]
Hi, 
when sending SMS by bash script I'm getting an error:

`/usr/local/smsapi/smsapi-bash-client/smsapi: line 76: SERVICE: invalid indirect expansion`

**My server configuration:**
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Sample command I'm using:
`/usr/local/smsapi/smsapi-bash-client/smsapi sms send --username XXX --password XXX TEL_NOS "abc"`

**Comment by smsapi** [comment]
You should use oauth. Here is instruction how to use it: https://github.com/smsapi/smsapi-bash-client#readme
